### PR TITLE
Update with release versioning, left navigator, doc reorganization & additional docs

### PR DESCRIPTION
**Pull request by mossuchida**
I have used new theme that is created for technical writer with features such as release versioning and left navigator.

I have also re-organized documentation (e.g. split & break down httpRequest, handlers), also added new docs that explain simple steps to create the benchmark YAML file in "building Blocks". It contains some conversations that we had in zulip (e.g. ISTIO support syntax, multiple core support, private http pools etc).

 Execution page explains different mode of execution : cli & web based.

Since the release versioning is enabled, original files are mostly reamed with 0.6_.... and included in the release-0.6 folder.  All files are in pages directory now.  sidebar is in _data/sidebars directory.

It uses additional tool to link to other pages easier, syntax of the links are changed.

### CODE REVIEW

**Comment by rvansa** [comment]
So it seems you've mixed moving to a new layout with actual content refactoring (splitting docs into chapters etc.), which makes such huge PR quite hard to review, explain the need for given change etc.

1) I see that you've inlined all the examples fetched from GitHub to the documentation. It would be very nice if we could do that in the gh pages build phase (ending up with static HTML only), but you've simply copy-pasted the examples that are part of distribution and are [validated for syntax correctness, serializability etc.](https://github.com/Hyperfoil/Hyperfoil/blob/master/distribution/src/test/java/io/hyperfoil/example/ValidateExampleTest.java) into docs. I am afraid that such change would make these files unmaintainable (how are you going to verify that these are correct?).

2) You've manually modified the reference from `docs/steps`, adding headers and restructuring some, pulling `httpRequest` and its handlers specifically to an upper level etc. Are you aware that all those files [are generated automatically](https://github.com/Hyperfoil/Hyperfoil/blob/master/distribution/src/main/java/io/hyperfoil/schema/DocsGenerator.java) (have you manually edited all those files?)? Adding the front matter is quite trivial, but I am quite opposed to let `httpRequest` step completely stick out.

3) You've create a documentation version for each release. I was considering that structure before but until we're in the pre-1.0 stage it's not beneficial to present any half-baked old documentation, suggesting that someone *could* use and older version. At this moment, last released version is the only version anyone should care about, and I wouldn't promote anything else. You were right in one of your earlier comments that we should start tracking release news/migration guide to explicitly warn about breaking changes we did, but that's it.
3.1) When I type 'basic' into the search bar I get results for both 0.5 and 0.6 without any visual indication. And btw. the tooltip there behaves weirdly, thought that might be my Firefox.

There are more issues (I feel rather uncomfortable with those huge CSS files where 99% probably isn't used, could that be minimized to drop the garbage?), not commiting DS_Store files (put that to `.gitignore` etc.) but let's deal with issues one at a time.

**Comment by rvansa** [comment]
3.2) How do you make sure that links from version X always go to version X, and not any previous version? Do you expect any scripts moving docs during the release process and updating all the links?

**Comment by mossuchida** [comment]
Hi, Radim, thank you for the review.  Here are the comments:

1. I didn't investigate enough to do this, so I just copied & pasted manually. I was going to figure out later how to do that in this layout.  btw, I have noticed original doc had issues with color highlighting, also line number was not right for some code.

2.  The huge steps doc was very confusing as they were all in the same level.  It took a while to figure out what was steps & what was processors until I start coding & experimenting.  Are you able to break them down in code? (Can you modify autogeneration to sort them out?). I have manually modified it for this version so that people can try out if it is easier to understand (it is easier to experiment if there is real example)  HTTPRequest steps are the main part in the yaml & huge, I wanted to separate them, but if you don't like, we can create a link from other pages that explain HTTPRequest & that is okay.

3. We can have single version for now, but doc should be able to handle multiple versions when we hit to 1.0.  I have removed News link, if you like, I can put it back (or we can just have a migration page)
3.1) I can check how to search with release information.  I have removed tooltips json, let me put it back.

We can clean up CSS files.  while looking through Jekyll themes, this theme looks more like professional clean look. also it had release versioning & left navigator, I picked it up even though it has more features than we need.  I tried to change your existing slate theme, but I gave up as I don't have enough time to learn Jekyll to make pages well.

btw, I am also promoting HF to currently assigned team (not with Surya), but they are not comfortable using HF, they want Gatling rather - their argument point is gatling has good doc to easily create benchmarks, also they have more contributors (7 vs 144 : well, they are paid product. 
 Senior tech lead likes Vegeta & it has 47 contributors).  I tried Visual Studio Code plugin, but if I don't know how to structure the benchmarks, it is no use.  We need steps to explain how to create each level of yaml file (building blocks/creating benchmarks section).
3.2) Each version start with version number . e.g. 0.6_  My thinking is to copy a release folder, then use a script (maybe sed) to change 0.6_ to 0.7_ or whatever.  sidebar didn't like 0.6_, I had to change it to 06_, I thought I could just use a script to overwrite with 06_ to 07_

**Comment by rvansa** [comment]
1. I am aware of the syntax highlight issues; I've invested just as much time into that to get the highlighting 'good enough'. The `rouge` highlighting probably does not suffer some of the issues, but it's static only. If you know about any other javascript-based syntax highlighter, or even better, a way to include github content to the pages, I am all for that.

2. I think you have a valid point, it's just that at this point I don't know how to structure it better. My intent was to have the *documentation* (install, reference...) explaining things top-bottom, from abstractions to concrete steps. Contrary to that the *quickstarts* provide bottom-top approach; this is what users should start with.
You've split some longer documents to sections (I can imagine the TLDR effect), I'd like to pick this up. IMO the ideal size of one page is about two screen scrolls (5 - 10 minutes reading).
I can adjust the generator, of course - it's rather about defining abstractions. As `httpRequest` starts getting really huge, for the starter moving that to extra page makes sense (I'll make an issue for that).
Note that I've split FAQ into FAQ and Troubleshooting, that's a good suggestion.

3. Agreed, 1.0 is the milestone for keeping different versions of documentation live.

TBH I don't think either of those themes/layouts look too professional - grabbing a pre-cooked theme and changing project name does not have that effect. Until we get a truly professional assistance, I'd like to keep things minimalistic and functional, and focus on the content and ease of its consumption than the whistles and bells around. That's why I would strongly  prefer adding improvements incrementally, with small PRs changing parts of the documentation that make it easy to show 'this is clearly better'. I am not convinced we need to scratch everything and start with completely different structure and layout.

The thing is that Gatling is really good as long as you don't need to run a distributed benchmark and you don't hit its other limits, needing features that stretch beyond the open-core business model. If I could avoid these I would gladly use it as well and focus on other things that benchmark framework development. I don't think it makes too much sense to push Hyperfoil just for it's own sake - Hyperfoil is here to solve certain problems, and the need for that must overweight all the risks with using something with small user base and current beta-quality (at best).

**Comment by rvansa** [comment]
I've added the side menu (still to refactor the reference a bit), check it out.

**Comment by mossuchida** [comment]
I agree with your points. Let me add some documentation that I really want for current user guide.

**Pull request closed without merging**
