### PR TITLE
Hyperfoil 0.24.2

### PR DESCRIPTION
**Pull request by shivam-sharma7**

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
review/ @jesperpedersen

**Comment by jesperpedersen** [comment]
Please, rebase

**Comment by jesperpedersen** [comment]
Doesn't look correct...

**Comment by shivam-sharma7** [comment]
> Doesn't look correct...

Squash and merge 1 Commit from this branch

**Comment by jesperpedersen** [comment]
https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

**Pull request closed without merging**
